#!/usr/bin/python3
import requests;
import sys;

argc = len(sys.argv);
if argc == 1:
    print("Usage:");
    print("  requrl <url> - show text on page");
if argc == 2:
    resp = requests.get(sys.argv[1]);
    print(resp.text);